name: Publish Package to npmjs
on:
  # 'release' allows publishing when the version changes.
  release:
    types: [published]
  # push:
  #   branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      # Added `npm install` to create package-lock.json file.
      - run: cd Mapping-System
      - run: npm install
      # end Added
      # npm ci requires package-lock.json file to exist.
      - run: npm ci
      - run: npm publish
      - run: cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
